// Command genparams writes internal/device/params_gen.go from the LinnStrument
// firmware's NRPN handlers: receivedNrpn (numbers, names, value ranges) and
// sendNrpnParameter (which parameters NRPN 299 can read back), in ls_midi.ino.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
)

type param struct {
	num      int
	name     string
	min, max int
	hasRange bool
}

var (
	caseRe  = regexp.MustCompile(`case (\d+):`)
	rangeRe = regexp.MustCompile(`inRange\(value, (-?\d+), (-?\d+)\)`)
)

func main() {
	src := flag.String("src", "", "path to ls_midi.ino")
	out := flag.String("out", "params_gen.go", "output file")
	flag.Parse()
	data, err := os.ReadFile(*src)
	if err != nil {
		log.Fatal(err)
	}
	lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
	params := parseReceived(body(lines, "void receivedNrpn("))
	readable := map[int]bool{}
	for _, n := range topLevelCases(body(lines, "void sendNrpnParameter(")) {
		readable[n] = true
	}
	if len(params) == 0 || len(readable) == 0 {
		log.Fatal("no parameters found; has the firmware source changed?")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genparams from linnstrument-firmware/ls_midi.ino. DO NOT EDIT.\n\n")
	b.WriteString("package device\n\n")
	b.WriteString("// firmwareParams lists the NRPN parameters the firmware accepts. Split parameters\n")
	b.WriteString("// (0-99) are for the left split; the right split uses the same number plus 100.\n")
	b.WriteString("var firmwareParams = []Param{\n")
	for _, p := range params {
		fmt.Fprintf(&b, "\t{Num: %d, Name: %q, Min: %d, Max: %d, HasRange: %v, Readable: %v},\n",
			p.num, p.name, p.min, p.max, p.hasRange, readable[p.num])
	}
	b.WriteString("}\n")
	src2, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src2, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s: %d parameters, %d readable\n", *out, len(params), len(readable))
}

// body returns the lines of the function starting with sig, up to its closing brace.
func body(lines []string, sig string) []string {
	for i, l := range lines {
		if strings.HasPrefix(l, sig) {
			for j := i + 1; j < len(lines); j++ {
				if strings.HasPrefix(lines[j], "}") {
					return lines[i+1 : j]
				}
			}
		}
	}
	log.Fatalf("function %q not found", sig)
	return nil
}

// isTopCase reports whether a line holds case labels of the outer switch (4-space indent).
func isTopCase(l string) bool {
	return strings.HasPrefix(l, "    case ") || strings.HasPrefix(l, "    case\t")
}

func topLevelCases(lines []string) []int {
	var out []int
	for _, l := range lines {
		if isTopCase(l) {
			for _, m := range caseRe.FindAllStringSubmatch(l, -1) {
				var n int
				fmt.Sscan(m[1], &n)
				out = append(out, n)
			}
		}
	}
	return out
}

// parseReceived collects each top-level case group with the comment above it and
// the first inRange(value, min, max) in its body.
func parseReceived(lines []string) []param {
	var out []param
	var comment, groupName string // the comment above a group names it
	var group []int
	var lo, hi int
	var hasRange, lastWasCase bool
	flush := func() {
		for i, n := range group {
			name := groupName
			if len(group) > 1 {
				name = fmt.Sprintf("%s %d", groupName, i+1)
			}
			out = append(out, param{n, name, lo, hi, hasRange})
		}
		group, hasRange, lo, hi = nil, false, 0, 0
	}
	for _, l := range lines {
		switch {
		case strings.HasPrefix(l, "    //"):
			comment = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(l), "//"))
			lastWasCase = false
		case isTopCase(l):
			if !lastWasCase {
				flush()
				groupName = comment
			}
			for _, m := range caseRe.FindAllStringSubmatch(l, -1) {
				var n int
				fmt.Sscan(m[1], &n)
				group = append(group, n)
			}
			lastWasCase = true
		default:
			if m := rangeRe.FindStringSubmatch(l); m != nil && len(group) > 0 && !hasRange {
				fmt.Sscan(m[1], &lo)
				fmt.Sscan(m[2], &hi)
				hasRange = true
			}
			if strings.TrimSpace(l) != "" {
				lastWasCase = false
			}
		}
	}
	flush()
	sort.Slice(out, func(i, j int) bool { return out[i].num < out[j].num })
	return out
}
